### PR TITLE
fix: rename hadolint input variable

### PR DESCRIPTION
**Pull request by jbergstroem**
`error-level` -> `error_level`

This doesn't address the warning that hadolint outputs since the action is set to not error on warnings. Let me know if you want me to address that too!

### CODE REVIEW

**Comment by jbergstroem** [comment]
Come to think of it, you can probably do `.dockerfile*` instead of listing them manually.

**Comment by 0xricksanchez** [comment]
Feel free for to add this to the PR. I’ll review it asap

**Comment by jbergstroem** [comment]
you could optionally also tell github to only run it if dockerfiles change

**Comment by 0xricksanchez** [comment]
> you could optionally also tell github to only run it if dockerfiles change

That’s something I wanted to do for all the checks for quite a bit. It probably should be done in a separate PR. Feel free to do so tho :)!

**Comment by jbergstroem** [comment]
@0xricksanchez: i believe i've accomplished whats needed in this PR then! I spent some time looking at the community using the action I maintain and wanted to help out / improve usage.

**Pull request merged**
